name: Build and Push Docker Image to DockerHub

on:
  push:
    branches:
      - main # Run workflow when changes are pushed to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps: 
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/angular-bird:latest
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/angular-bird:latest
